Wispro with openresty & redis
sequre/wispro_installer pull request #7
Opened 2018-10-25 18:34 UTC by Shelvak

2018-10-26 14:48 UTC, luchano requested changes
Me parece que hay cosas que sobran, fijate el comment

2018-10-26 14:48 UTC, luchano commented on wispro
> +      start_openresty
te quedaron varias de estas de openrestry que hay que hacer pi-ha

2018-10-26 16:57 UTC, Shelvak commented on wispro
> +      start_openresty
No había pushado, perdona

2018-10-30 13:15 UTC, Shelvak commented on wispro
> +    echo "waking up postgres"
```suggestion
    echo "waking up redis"
```

2018-10-30 13:24 UTC, merged